apiVersion: v1
kind: Service
metadata:
  name: {{ include "easy-school.fullname" . }}
  labels:
    {{- include "easy-school.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    {{- include "easy-school.selectorLabels" . | nindent 4 }}
