name: Destroy AWS Resource

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: capstone_ecr_repo           # set this to your Amazon ECR repository name

jobs:
  destroy-resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: infra  # The branch that contains the Terraform code

          
      # Configure AWS credentials
      #====================================#
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #======================================#
      # Install Terraform and its dependencies
      #======================================#
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.8.5

      #================================#
      # Dynamically create tfvars file
      #================================#
      - name: Generate tfvars file
        id: tfvars
        run: |
          touch prod.tfvars
          echo "aws_region = \"${{ env.AWS_REGION }}\"" >> prod.tfvars
          echo "aws_ecr_repo_name = \"${{ env.ECR_REPOSITORY }}\"" >> prod.tfvars

          cat prod.tfvars
        working-directory: infra/
      

      #=============================#
      # Terraform Init
      #=============================#
      - name: Terraform Init
        id: init
        run: terraform init   
        working-directory: infra/

        
      #=============================#
      # Terraform Validate.
      #=============================#
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -var-file="prod.tfvars" -no-color -auto-approve
        working-directory: infra/
        continue-on-error: true